// src/vue/components/Counter.vue
<template>
	<div class="counter">
		<input type="count" v-model="count" readonly />
		<button type="button" @click="count += 1">+</button>
		<button type="button" @click="count -= 1">-</button>
	</div>
</template>

<script>
export default {
  name: "Counter",
  data() {
	  return {
		  count: 0
	  }
  },
};
</script>

// src/react/components/Counter.jsx
import React, { useState } from 'react';

const Counter = () => {
    const [ count, setCount ] = useState(0);

    return (
        <div className="counter">
            <input type="count" value={count} readOnly />
            <button type="button" onClick={() => setCount(count + 1)}>+</button>
            <button type="button" onClick={() => setCount(count - 1)}>-</button>
        </div>
    )
}

export default Counter;
